# Generated by Django 4.2.14 on 2024-08-09 17:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('trainer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateField(default=django.utils.timezone.now)),
                ('training_type_other', models.CharField(blank=True, max_length=100, null=True)),
                ('training_id', models.CharField(max_length=100, unique=True)),
                ('training_name', models.CharField(blank=True, max_length=100, null=True)),
                ('training_image', models.ImageField(blank=True, null=True, upload_to='training_images/')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateField(default=django.utils.timezone.now)),
                ('trainer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.trainer')),
                ('training', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='trainings.training')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.trainingtype')),
                ('whitelevel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.company')),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='training_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.trainingtype'),
        ),
        migrations.AddField(
            model_name='training',
            name='whitelevel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.company'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='trainings.training'),
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_name', models.CharField(max_length=100)),
                ('trainee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainees', to='trainings.training')),
            ],
        ),
    ]
