# Generated by Django 5.0.6 on 2024-12-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='about_the_training',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
    ]
