version: '3.8'

services:
  web:
    build: .
    command: gunicorn EMS.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8080:8000"
    environment:
      SECRET_KEY: your_production_secret_key
      DEBUG: 'True'
      ALLOWED_HOSTS: '0.0.0.0,127.0.0.1,localhost,192.168.0.166'
      DB_NAME: ems
      DB_USER: jd
      DB_PASSWORD: root
      DB_HOST: db
      DB_PORT: '5432'
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      CORS_ALLOW_ALL_ORIGINS: 'True'
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      POSTGRES_DB: ems
      POSTGRES_USER: jd
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
