# Generated by Django 4.2.14 on 2024-08-09 17:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_report_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Accident Reports',
            },
        ),
        migrations.CreateModel(
            name='AccidentReportedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccidentReporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_reporting_date', models.DateField(default=django.utils.timezone.now)),
                ('accident_id', models.CharField(max_length=20, unique=True)),
                ('toolbox_train', models.BooleanField(default=False)),
                ('accident_image', models.ImageField(blank=True, null=True, upload_to='accident_images/')),
                ('about_the_accident', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccidentSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccidentType',
            fields=[
                ('accident_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('accident_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PermitStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PpeStatus',
            fields=[
                ('ppe_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('ppe_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('severity_id', models.AutoField(primary_key=True, serialize=False)),
                ('severity_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AccidentWorkman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workmen', to='accident.accidentreporting')),
            ],
        ),
    ]
