# Generated by Django 4.2.14 on 2024-08-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('accident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentworkman',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='accidentsupervisor',
            name='accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='accident.accidentreporting'),
        ),
        migrations.AddField(
            model_name='accidentsupervisor',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='accidentreporting',
            name='accident_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accident.accidenttype'),
        ),
        migrations.AddField(
            model_name='accidentreporting',
            name='permit_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accident.permitstatus'),
        ),
        migrations.AddField(
            model_name='accidentreporting',
            name='ppe_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accident.ppestatus'),
        ),
        migrations.AddField(
            model_name='accidentreporting',
            name='severity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accident.severity'),
        ),
    ]
