# Generated by Django 4.2.14 on 2024-08-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('accident', '0002_initial'),
        ('trainings', '0001_initial'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentreporting',
            name='toolbox_reference_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.training'),
        ),
        migrations.AddField(
            model_name='accidentreporting',
            name='whitelevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.company'),
        ),
        migrations.AddField(
            model_name='accidentreportedby',
            name='accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to='accident.accidentreporting'),
        ),
        migrations.AddField(
            model_name='accidentreportedby',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='accident_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accident.accidentreporting'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='accident_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accident.accidenttype'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='severity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accident.severity'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='whitelevel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.company'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='workmen_involved',
            field=models.ManyToManyField(to='accident.accidentworkman'),
        ),
    ]
