# Generated by Django 4.2.14 on 2024-08-09 17:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedThings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedToEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('item_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_type_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewIssuance',
            fields=[
                ('issuance_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('issuance_date', models.DateField(default=django.utils.timezone.now)),
                ('newIssuance_image', models.ImageField(blank=True, null=True, upload_to='newIssuance_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ItemValidity',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ITEM.item')),
                ('validity_in_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_days', models.IntegerField()),
                ('issue_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ITEM.newissuance')),
                ('issued_thing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_issue', to='ITEM.issuedthings')),
            ],
        ),
    ]
