# Generated by Django 4.2.14 on 2024-08-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('ITEM', '0001_initial'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newissuance',
            name='white_level_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.company'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ITEM.itemtype'),
        ),
        migrations.AddField(
            model_name='issuedtoemployee',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='issuedtoemployee',
            name='issue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ITEM.newissuance'),
        ),
        migrations.AddField(
            model_name='issuedthings',
            name='issue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ITEM.newissuance'),
        ),
        migrations.AddField(
            model_name='issuedthings',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ITEM.itemvalidity'),
        ),
    ]
