# Generated by Django 5.0.6 on 2024-12-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITEM', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newissuance',
            name='about_the_newissuance',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
    ]
