# Generated by Django 5.0.7 on 2025-01-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ITEM", "0003_newissuance_about_the_newissuance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newissuance",
            name="newIssuance_image",
            field=models.ImageField(
                blank=True, default="null", null=True, upload_to="newIssuance_images/"
            ),
        ),
    ]
