# Generated by Django 4.2.14 on 2024-08-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='whitelevel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.company'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('employee_id', 'whitelevel_id')},
        ),
    ]
