# Generated by Django 5.0.6 on 2025-01-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
